### ISSUE TITLE
CI: sync Arrow Meta with Kotlin compiler

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-meta#189]
Previous steps 
- [x] How to build Kotlin Compiler
- [x] How to schedule actions
- [x] How to get the release tags in a period of time
- [x] How to use a local dist of Kotlin Compiler
- [x] How to create an issue
- [x] How to add content from files in the script to create an issue
- [x] How to get the data from new Kotlin Compiler releases

Tasks
- [x] Build the project with the last version of Kotlin compiler in development
- [x] Create issue in case of failure
- [x] Create a PR to update the versions in case of success

**Comment by rachelcarmena** [comment]
## Notes

- [The Kotlin plugin for Intellij IDEA](https://plugins.jetbrains.com/plugin/6954-kotlin/versions) doesn't follow the DEV and EAP versions by Kotlin Compiler, so I'll fix this version for it:
```
idea-plugin/build.gradle

setPlugins("gradle", "java", "org.jetbrains.kotlin:${KOTLIN_VERSION}-release-IJ2019.2-1")
```

**Comment by rachelcarmena** [comment]
Solved in #204
