### ISSUE TITLE
Arrow Meta Gradle Plugin: publish snapshots in OSS

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-meta#362]
- [x] Publish snapshots for Gradle Plugin in OSS (oss.jfrog.org)
- [x] Use Gradle Plugin Portal for releases
- [x] Update documentation.
- [x] Update Gradle Plugin metadata.
- [x] Remove badge.
- [x] Update examples.
- [x] Migrate Gradle Plugin Portal account to Arrow Kt (because we're depending on my personal account for Gradle Plugin now)

**Comment by rachelcarmena** [comment]
Solved in #361

**Comment by rachelcarmena** [comment]
I've created this issue to remove the current plugin https://github.com/gradle/plugin-portal-requests/issues/28 and to create it again from a different account (@franciscodr is helping me with it).

**Comment by rachelcarmena** [comment]
`GRADLE_PUBLISH_KEY` and `GRADLE_PUBLISH_SECRET` have been updated by @franciscodr :clap: :clap: :clap: 

Now, waiting for https://github.com/gradle/plugin-portal-requests/issues/28

**Comment by rachelcarmena** [comment]
Answer from Gradle team!! :tada: It will be done tomorrow morning :+1:

**Comment by rachelcarmena** [comment]
Done!! Really kind attention from Gradle team :heart:
