### ISSUE TITLE
[Feature Epic] Coercion

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow-meta#567]
This covers the complete Coercion feature.

#### When explicit: 

* [x] Applicable Inspection to highlight the expression (as warning) and show a quick fix to convert to implicit 
* [ ] Use the inspection text to show a clarification on why you’d wanna use the proof. Show types From ~> To and link to the proof declaration. 

#### When implicit: 

* [x] Applicable Inspection to highlight the expression (as information) and show a quick fix to convert to explicit.
* [ ] Use the inspection text to show a clarification on what’s happening. Show types From ~> To and link to the proof declaration.
* [ ] Line marker that explains the coercion being used.
