### ISSUE TITLE
[Feature Epic] Tuples

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow-meta#568]
This covers the complete Tuples feature.

### Requirements

* [ ] Tests for the feature
* [ ] Documentation
* [x] Fold tuples from e.g: Tuple2<A, B> to (A, B) for readability. Only for the parent tuple, we don’t want to fold nested tuples.
* [x] Listen to caret and collapse all folding regions in the document except for the current line one. That gets expanded on click.
* [x] Click folded tuple to unfold it. E.g: (A, B) -> Tuple2<A, B>.
* [ ] Line marker with icon and explanation that clarifies what is happening when folded.
* [ ] Add ellipsis / truncate in the end when there are more than 5 elements in the tuple.
