### ISSUE TITLE
[Feature Epic] Union types

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow-meta#570]
This covers the complete Union types feature.

### Requirements

* [ ] Tests for the feature
* [ ] Documentation
* [x] Fold union types e.g: Union2<A, B> to A | B for readability. Only for the parent union, we don’t want to fold nested unions. If we collapse we want to collapse all, not child by child.
* [x] When folding, if the Union is null (e.g: Union2<A, B>?), we want to show in the placeholder the types in the union followed by null (e.g: A | B | null) 
* [x] When folding, nested Unions are not reflected since they are redundan, we only show the types (e.g: Union2<A, Union2<B, C>> -> A | B | C) 
* [x] When folding, redundant types are erased. (e.g: Union3<Int, String, Int> -> Int | String) (also for nested nullable types) 
* [x] Listen to caret and collapse all union types in the document except for the current line one. That gets expanded on click. 
* [x] Click folded union type to unfold it. E.g: A | B -> Union2<A, B>. 
* [ ] Line marker with icon and explanation that clarifies what is happening when folded.
* [x] Add ellipsis / truncate in the end when there are more than 5 elements in the tuple. ✅

**Comment by DanielSWolf** [comment]
I'd love to use union types, but [the documentation](https://meta.arrow-kt.io/docs/apidocs/compiler-plugin/arrow.meta.plugins.union/union-types.html) appears to be more of a stub. I found the [unit test suite](https://github.com/arrow-kt/arrow-meta/blob/main/compiler-plugin/src/test/kotlin/arrow/meta/plugins/union/UnionTest.kt), which helped me understand the basic syntax. However, I'm still not sure what's the best practice for switching over the possible types of a union. I'd appreciate some more documentation.
