### ISSUE TITLE
[Feature Epic] Refined types

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow-meta#571]
This covers the complete Refined types feature.

### Requirements

* [ ] Tests for the feature
* [ ] Documentation
* [ ] Declarations: If class is annotated with @Refinement, show line marker with icon explaining what’s happening. Line marker is there, but we need to polish what to show inside.
* [ ] Declaration: Be able to autofold to show only the predicates (literals).
* [ ]Listen to caret and collapse all union types in the document except for the current line one. That gets expanded on click.
* [ ]When clicking a folded refinement -> unfold.
* [ ]Call sites: Line marker that shows a refinement being used, explains what’s happening and links to the refinement declaration. 
* [ ] Call sites: When a predicate is not complied we must show an error highlight clarifying which one is not complying. Show all literals in Light grey and the one failing highlighted in red.

**Comment by abdulkaderjeelani** [comment]
Is the @refinement annotation part of the libarary, I tried to use it in my code with no luck. I am using "0.11.0". I can use @optics annotation without any issues.
