### ISSUE TITLE
SMT research Epic

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow-meta#576]
This issue aggregates sub-issues for automated query derivation regarding specific goals.

#### Goal : Query derivation
- [ ] based on Pre- and Postconditions. Top-bottom,  Bottom-up
- [ ] based on Liquid Types

#### Goal : Totality 
- [ ] Totality of expressions
- [ ] Totality of functions
- [ ] Totality of programs 

#### Goal : Termination
- [ ] Termination of functions
- [ ] Termination of programs 

#### Goal : Synthesis
This goal refers to the translation process of any given AST to the one for TIP or SMT.

Feel free to refine this issue.

**Comment by serras** [comment]
To give an overview of what I have in mind, the goal is to implement something akin to Liquid Types for the corresponding AST. There are [two](http://goto.ucsd.edu/~rjhala/liquid/liquid_types.pdf) [papers](http://goto.ucsd.edu/~rjhala/papers/abstract_refinement_types.pdf) which describe how to use them, and [another one](http://goto.ucsd.edu/~rjhala/papers/refinement_types_for_haskell.pdf) describing the integration with Haskell. The latter is interesting because they explain how to check totality and termination within the same framework.

I have a rough idea of how we can engineer this in such a way that "pre/postconditions", "totality", and "termination" are just instantiations of a more general framework. [CiaoPP](https://ciao-lang.org/ciao/build/doc/ciaopp.html/) takes a similar focus, although they use a different technique called _abstract interpretation_. Roughly, each node in the AST can add information to the query, and after traversing a whole function we send this query to the SMT solver, which then says "yes", "don't know", or gives a counter-example.

There are some questions to know before embarking in writing the rules / algorithm:

- What are the kind of nodes that we have in the AST?
- Do we have type information available for those nodes? Tools like LiquidHaskell take the stance that checking properties is much easier once you've dealt with types. So having that info in a generic form would be awesome. Alas, we might lose some interesting interactions with type proofs.
- Can we attach any information we like to functions? Right now we want to have: precondition for each argument, maybe dependently, postcondition for the result; and then function-wide information about totality and exhaustiveness.

@i-walker can you maybe answer those questions?
@raulraja does this sound like a good plan to you?
Both: please check [CiaoPP](http://cliplab.org/papers/ciaopp-tutorial.pdf), it's a wonderful tool, except that it targets Prolog and Emacs, except a common language and an IDE ;)

**Comment by serras** [comment]
[Synquid and ReSyn](https://github.com/tjknoth/resyn) show how refinement types can help into generating code (that is, _synthesis_). The algorithm itself is not that complex once you get into refinement types: essentially figure out what are the possible terms by checking its non-refined type, and choose those which satisfy the corresponding query. If the solver says "don't know", try to pattern match, as that introduces more information into the system.

The cool thing is that such a synthesis engine is _generic_ over the domains to check. For example, if you want to define a "pure" function, the system would automatically know what using a non-pure one is not allowed, since it does not satisfy the corresponding query.

**Comment by serras** [comment]
@i-walker pointed me towards the current [refinements](https://github.com/arrow-kt/arrow-meta/blob/master/compiler-plugin/src/test/kotlin/arrow/meta/plugins/refinement/RefinementTests.kt), which I had completely forgotten about!

@i-walker @raulraja I need input from you (or anybody else in the Meta project) here :)

What is called a refinement in your system, it's called a *measure*  in Liquid Types. However, there are two important difference: 
- You can apply *several* measures to the same value. This is kind of important, because you may want to keep several invariants over the same value, like non-nullity of a list, or containing a specific element.
- Measures may not only be Boolean properties, but also integers or sets. We can however implement those using _parametric_ properties, sort of:

    ```kotlin
    @Refinement inline class GreaterThan(val n: Int, val value: Int)  {
      companion object : Refined<Int, GreaterThan> {
        override val target : (Int) -> GreaterThan = ::GreaterThan
        override val validate: Int.() -> Map<String, Boolean> = {
          mapOf(
            "Should be >= " to (this >= n)
          )
        }
      }
    }

    @Coercion
    fun Int.greaterThan(n): GreaterThan? =
      GreaterThan.from(n, this)
    ```

    However, this is problematic. How would we write the type signature of a function which takes something greater than 2 and returns something greater than 4? How do we express those numbers so that they are available when we look at the refinements? Or how would **you** envision this?

I am pretty sure that once this is figured out, adding SMT support would be easy! Essentially, what we want to achieve is simply a more clever `Refinement` solver which knows how to deal with variables.

**Comment by raulraja** [comment]
@serras your plan sounds good. Let's discuss over a meeting the approach. Kotlin does not have refined types. Kotlin has compile time evaluable complex expressions given any library that is added by a plugin to the compiler classpath. Also I would like to see how you envision some.od the features we are building in Kotlin coming from a Haskell background.

**Comment by raulraja** [comment]
@typechecking is possible in All Lang plugins that have implemented it but it's not part of the psi layer. The psi layers gives you all info about the tokens being functions, variables and their type or lacking infected type. But expressions based on libraries that exist in the compiler classpath and are pure can be typechecked by evaluating in the compilation process which is how we do it in Kotlin

**Comment by raulraja** [comment]
Kotlin for example has the notion of KtExpression which is essentially anything that is reducible to a value and you can analize indepently to get it's type. The Kotlin contract support is similar but it's kind of limited. I like the idea of supporting all expressions
