### ISSUE TITLE
@With proposal Epic

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow-meta#770]
Preliminary roadmap to reencode @Given with @With for multiple receivers, as discussed in this [roadmap](https://youtrack.jetbrains.com/issue/KT-42435). 
Please add or update related issues here.

@With:
- [x] N Packages up to 22 e.g.: @with<A, B, C, ...>
- [ ] `val With: Nothing = TODO("Same as arrow.given")` as an instance provider
- [ ] Variance https://github.com/arrow-kt/arrow-meta/issues/773

Compiler: 
- [x] Auto-Import arrow-meta-prelude https://github.com/arrow-kt/arrow-meta/issues/772
- [ ] `in Analysis`: check for conflicting declarations when clashes occur by multiple receivers
- [ ] `in SyntheticResolution`: Populate SyntheticResolution and related Memberscope without specifying this with extra specifiers https://github.com/arrow-kt/arrow-meta/issues/774
- [ ] Suppress Diagnostic Error's (Same as for Given)
- [ ] `in Ir`: Populate Dispatcher, ExtensionReceiver accordingly, as to which Receiver is being used at each call-site https://github.com/arrow-kt/arrow-meta/issues/775

IDE: 
- [x] Auto-Import arrow-meta-prelude https://github.com/arrow-kt/arrow-meta/issues/772
- [ ] Annotators for conflicting declarations when clashes occur by multiple receivers
- [ ] Populate SyntheticResolution and related Memberscope without specifying this with extra specifiers https://github.com/arrow-kt/arrow-meta/issues/774
- [ ] Suppress Diagnostic Error's (Same as for Given)
- [ ] Suppress Intelli-Sense to suggest extra specifiers for `this`
